CASMINST-2459
Cray-HPE/node-image-build pull request #125
Opened 2021-12-06 16:45 UTC by manderson-hpe

#### Summary and Scope

Relates to CASMINST-2549 to add GCP builds of NCN images. This branch is specific to develop and SP3.

This code adds the ability to build GCP images. The base layer is built locally and then it is uploaded to GCP. From there the common and ncn-node layers are built in GCP. 

Upon review, attention should be focused on the only, except lines of the Packer configuration. These directives determine if the code is executed on metal (virtualbox, qemu), or cloud (googlecompute), or both.

#### Prerequisites

- [x] I have included documentation in my PR (or it is not required)
- [x] I tested this on building in Jenkins
- [x] https://github.com/Cray-HPE/csm-rpms/pull/158
- [ ] https://github.com/Cray-HPE/csm-shared-library/pull/19

2021-12-09 22:26 UTC, rustydb requested changes

2021-12-09 22:26 UTC, rustydb commented on Jenkinsfile.github
Does anything in `release` need to be done for google, or do the release tags publish automagically? (e.g. how does a stable Google image publish to GCP?)

2021-12-09 22:26 UTC, rustydb commented on boxes/ncn-common/common.pkr.hcl
> +  machine_type = "n2-standard-32"
@mtupitsyn is this already in the Jenkins env from which we could grab it from?

2021-12-09 22:26 UTC, rustydb commented on boxes/ncn-common/common.pkr.hcl
> +    only = ["googlecompute.ncn-common"]
The `only/except` usage might get confusing if we ever add another endpoint, like AWS.
Otherwise I like it.

2021-12-09 22:26 UTC, rustydb commented on boxes/ncn-common/common.pkr.hcl
> +    except = ["googlecompute.ncn-common"]
Shouldn't this also run for Google, or does it cause problems?

2021-12-09 22:26 UTC, rustydb commented on boxes/ncn-common/common.pkr.hcl
> +    except = ["googlecompute.ncn-common"]
nit: This should be _only_, explicitly stating that `provisioners/metal/hpc.sh` is metal deliverables only.

2021-12-09 22:26 UTC, rustydb commented on boxes/ncn-common/common.pkr.hcl
> +    except = ["googlecompute.ncn-common"]
nit: This should be _only_, explicitly stating that `metal.packages` is metal deliverables only.

2021-12-09 22:26 UTC, rustydb commented on boxes/ncn-common/common.pkr.hcl
Isn't there a new google.packages file, are we not calling that at all?

2021-12-09 22:26 UTC, rustydb commented on boxes/ncn-common/common.pkr.hcl
> +    only = ["googlecompute.ncn-common"]
I forgot about vbox.
Do you want vbox collecting this as well? Right now vbox is basically google+metal together.

2021-12-09 22:26 UTC, rustydb commented on boxes/ncn-common/files/tests/common/goss-image-common.yaml
> -  /etc/zypp/services.d/Basesystem_Module_15_SP3_x86_64.service:
@manderson-hpe were these removed due to a failing test? @heemstra would this mean repos would appear? @manderson-hpe we should boot test these and verify 0 repos appear on metal (gcp is different, it should have some appear IIRC how the old pipeline worked).

2021-12-09 22:26 UTC, rustydb commented on boxes/ncn-common/files/scripts/common/cleanup.sh
> -echo "purging buildonly repos"
Why are these lines removed, did they cause issues or was it not necessary? These were pre-cautions for ensuring no repos appeared in booted images.

This would contradict my previous comment, but this alludes to the idea that we cleanup the _added_ repos.

Line 10-14 were added more recently, those might actually only want to run on metal.. @heemstra and @manderson-hpe don't forget that we haven't had GCP images for a long time so there might be changes that aren't kosher for google inside our `common` provisioners and scripts (be aware).

2021-12-09 22:26 UTC, rustydb commented on boxes/ncn-node-images/ceph/files/scripts/metal/zeros.sh
> -#!/bin/bash
@cdelatte-hpe or @brantk-hpe should comment here, this had been added for a specific reason IIRC.

2021-12-09 22:26 UTC, rustydb commented on boxes/ncn-common/files/tests/common/goss-image-common.yaml
> -  /etc/zypp/services.d/Basesystem_Module_15_SP3_x86_64.service:
Never mind, I see that these were moved into `../metal/`.

2021-12-09 22:26 UTC, rustydb commented on boxes/ncn-node-images/node-images.pkr.hcl
>      only = [
This `only` should be removed, we want `base.packages` in everything.

2021-12-09 22:26 UTC, rustydb commented on boxes/ncn-node-images/node-images.pkr.hcl
> +      "bash -c '. /srv/cray/csm-rpms/scripts/rpm-functions.sh; install-packages /srv/cray/csm-rpms/packages/node-image-kubernetes/base.packages'"]
(if not, just resolve this comment).

2021-12-09 22:27 UTC, rustydb commented on boxes/ncn-common/files/scripts/common/cleanup.sh
> -echo "purging buildonly repos"
conversation moved to https://github.com/Cray-HPE/node-image-build/pull/125#discussion_r766202176

2021-12-10 14:36 UTC, manderson-hpe commented on Jenkinsfile.github
> +def buildGoogle = false
I agree and setting it to false was more of a question. We can easily switch it to true and it'll build all the time but I think we need some follow up tickets?

- How do releases work with promoting GCP builds?
- How do we clean up old GCP builds?

I generally didn't want to impede the normal builds with this, but I can enable it.

2021-12-10 14:56 UTC, manderson-hpe commented on Jenkinsfile.github
> +                                sh "./scripts/google/import.sh"
The base image is the same for QEMU and for GCP. We just upload the QEMU base image to GCP and GCP converts it. We could also upload a vbox image, etc.

2021-12-10 14:58 UTC, manderson-hpe commented on Jenkinsfile.github
> +                stage('GCP - QEMU Common') {
Copy paste is hard. I have updated all of the entries in the Jenkins file to be appropriately named.

2021-12-10 15:06 UTC, manderson-hpe commented on Jenkinsfile.github
> +                stage('GCP - QEMU Kubernetes') {
Fixed.

2021-12-10 15:16 UTC, manderson-hpe commented on boxes/ncn-node-images/node-images.pkr.hcl
> +      "bash -c '. /srv/cray/csm-rpms/scripts/rpm-functions.sh; install-packages /srv/cray/csm-rpms/packages/node-image-kubernetes/base.packages'"]
I don't think so. We are planning on cleaning this up with the csm-rpms effort so we can keep this in mind as we approach that.

2021-12-10 15:26 UTC, manderson-hpe commented on boxes/ncn-node-images/node-images.pkr.hcl
> +      "virtualbox-ovf.kubernetes",
Previously it was only on QEMU. I do see a benefit of getting the list, but there might be some more organization needed around it. A similar issue exists with the output of the goss tests.

2021-12-10 15:32 UTC, rustydb commented on Jenkinsfile.github
> +                stage('GCP - QEMU Common') {
Ok, resolve this comment then after you push (since I don't see updates yet).

2021-12-10 15:32 UTC, rustydb commented on Jenkinsfile.github
> +                                sh "./scripts/google/import.sh"
Gotcha, so this stage builds both targets.

2021-12-10 15:33 UTC, rustydb commented on Jenkinsfile.github
> +def buildGoogle = false
Right.

In general, the GCP and metal builds run in parallel and then for promotion we just push the renamed images into arti.
I think the old `nodeImageHelpers.py` file has code, or the `release.sh` script does for promoting both metal & GCP.

2021-12-10 15:34 UTC, manderson-hpe commented on Jenkinsfile.github
> +                stage('GCP - QEMU Ceph') {
It's not upload, they are built in GCP. I fixed everything to be named appropriately though.

2021-12-10 15:35 UTC, manderson-hpe commented on Jenkinsfile.github
This is a good question and I'm looking for input here. I asked this question in a previous comment.

2021-12-10 15:36 UTC, manderson-hpe commented on boxes/ncn-common/common.pkr.hcl
> +  machine_type = "n2-standard-32"
This is specific to Packer and how it boots VMs. I don't think we can (nor should) use something else. But I'm open to suggestions if we should.

2021-12-10 15:56 UTC, manderson-hpe commented on boxes/ncn-common/common.pkr.hcl
> +    only = ["googlecompute.ncn-common"]
Vbox should be identical to QEMU. The only stages we run solely on QEMU are related to the outputs we need, which include KIS artifacts and other stuff.

2021-12-10 15:57 UTC, manderson-hpe commented on boxes/ncn-common/common.pkr.hcl
> +    except = ["googlecompute.ncn-common"]
It causes problems. We would need to add a lot of conditionals to put them in different locations, etc.

2021-12-10 15:58 UTC, manderson-hpe commented on boxes/ncn-common/common.pkr.hcl
> +    except = ["googlecompute.ncn-common"]
This runs on vbox and qemu. So I can change it to be only vbox and qemu but I like the concise aspect of except.

2021-12-10 16:07 UTC, manderson-hpe commented on boxes/ncn-common/common.pkr.hcl
> +    except = ["googlecompute.ncn-common"]
This runs on vbox and qemu.

2021-12-10 16:15 UTC, manderson-hpe commented on boxes/ncn-common/common.pkr.hcl
There's nothing specific needed for google at this stage. I had added one when I was debugging the lvm2 issue, but we resolved that. As people use vshata I presume there will be a need for it.

2021-12-10 16:16 UTC, manderson-hpe commented on boxes/ncn-common/common.pkr.hcl
> +    except = ["googlecompute.ncn-common"]
It causes issues when we pull files. We also have a goss tests initiative that can take this effort on.

2021-12-10 16:21 UTC, manderson-hpe commented on boxes/ncn-common/common.pkr.hcl
> +    except = ["googlecompute.ncn-common"]
correct.

2021-12-10 16:22 UTC, manderson-hpe commented on boxes/ncn-node-images/ceph/files/scripts/metal/zeros.sh
> -#!/bin/bash
I merged these files into one common location to reduce complexity.

2021-12-10 16:23 UTC, manderson-hpe commented on boxes/ncn-node-images/k8s/files/tests/metal/goss-image-common.yaml
> +  /etc/zypp/services.d/Basesystem_Module_15_SP2_x86_64.service:
More info on this: We can't remove these service repos from the GCP images because they are used to validate the license and install required GCP packages on import and update. So this all needed to be moved to the end of the build process.

2021-12-10 16:44 UTC, manderson-hpe commented on boxes/ncn-node-images/provisioners/metal/cleanup.sh
> +SLES_VERSION=$(grep -i VERSION= /etc/os-release | tr -d '"' | cut -d '-' -f2)
buildonly repos are cleaned up at the base layer with a cleanup.sh script. In the node-images and common layers the rpm-functions.sh file is used. `cleanup-package-repos` function includes the necessary code.

2021-12-10 20:07 UTC, rustydb approved these changes

2021-12-10 20:09 UTC, rustydb commented
@manderson-hpe I rebased this and combined two of your commits (there were two with duplicate commit-messages). After it builds we can merge, unless another metal person has anything to say.

2021-12-10 21:14 UTC, rustydb commented
Branch failure.

2021-12-13 19:29 UTC, rustydb approved these changes

2021-12-13 20:13 UTC, rustydb requested changes
Remove https://github.com/Cray-HPE/node-image-build/blob/CASMINST-2549/boxes/ncn-common/provisioners/common/setup.sh#L6

2021-12-14 17:45 UTC, rustydb approved these changes

2021-12-14 19:31 UTC, manderson-hpe commented
/fast-forward

2021-12-14 19:37 UTC, rustydb commented
/fast-forward

2021-12-14 19:37 UTC, merged