MTL-1588 Remove Risk of Connection Loss
Cray-HPE/node-image-build pull request #139
Opened 2021-12-20 23:46 UTC by rustydb

#### Summary and Scope

- Fixes MTL-1588

##### Issue Type

- Bugfix Pull Request

The cold reset is very harsh on servers where a warm reset is
sufficient. On HPE, a warm reset will kick-over DHCP/static IPsrcs and
return faster.

This change pivots HPE servers to always warm reset instead of cold
resetting.

#### Prerequisites

- [x] I have included documentation in my PR (or it is not required)
- [x] I tested this on metal (e.g. an internal system, with hardware) (x) (if yes, please include results or a description of the test)
- [ ] I tested this on vshasta (if yes, please include results or a description of the test)
 
#### Idempotency
 

 
#### Risks and Mitigations

2021-12-20 23:49 UTC, heemstra requested changes

2021-12-20 23:49 UTC, heemstra commented on boxes/ncn-common/files/scripts/metal/install.sh
> +            ;;
what happens if ipmitool throws an error here?

2021-12-20 23:49 UTC, heemstra commented on boxes/ncn-common/files/scripts/metal/net-init.sh
> +# This function runs cloud-init commands twice; once to generate the
what?

2021-12-20 23:51 UTC, rustydb commented on boxes/ncn-common/files/scripts/metal/install.sh
> +            ;;
The default is `cold`, so it'll run that instead.

I could move this into `metal-lib.sh` and make it a _global_, since this is the same code for the efibootmgr section just copy-pasted and stripped.

2021-12-20 23:52 UTC, rustydb commented on boxes/ncn-common/files/scripts/metal/net-init.sh
> +# This function runs cloud-init commands twice; once to generate the
Exactly!

2021-12-21 01:32 UTC, rustydb commented
/fast-forward

2021-12-21 01:33 UTC, merged

2021-12-21 17:40 UTC, rustydb commented
This was yanked out of develop, syntax error.
Since we don't do merge commits, I deleted the commit and then tagged 0.2.35-2 on the `HEAD^`.
A new PR is incoming.