Add ability to build Live CD for PIT node
Cray-HPE/node-image-build pull request #154
Opened 2022-01-18 21:18 UTC by manderson-hpe

#### Summary and Scope

- Adds the ability to build a the live CD in the form of a qcow2 disk image, or a GCP disk image. The GCP disk image can be booted directly in GCP. The qcow2 image can be converted to a raw image and written directly to a USB disk. 

#### Prerequisites

- [ ] csm-rpms feature/livecd-gcp
 

 
#### Risks and Mitigations
 
- The disk sizes have been altered such that we start with a small disk for the `base` and `pit-common` layers. In subsequent layers the root disk is expanded to meet the needs of the image being built. Since we are building in both local VMs (QEMU) and cloud VMs (GCP) the disks change depending on the environment. The script finds the relevant disk and expands is to the maximum available based on VM disk size settings during the packer build process.

2022-01-26 01:04 UTC, rustydb requested changes
I reviewed some of it but there's some glaring issues, specifically cloud-init files exist in pit-common.

Also the csm-rpms default branch is set incorrectly for a merge to develop to be completed.

2022-01-26 01:04 UTC, rustydb commented on Jenkinsfile.github
> +        string(name: 'csmRpmBranch', defaultValue: "feature/livecd-gcp", description: 'The branch or ref to use when checking out csm-rpm repo for repo list and package lock versions.')
This needs to go back to release/1.2 before merging, I suspect you're merging csm-rpms:feature/livecd-gcp or is that merged? I'll look, seeing this value makes me thing initially it isn't merged yet.

2022-01-26 01:04 UTC, rustydb commented on boxes/pit-common/files/resources/common/cloud.cfg
> +## template: jinja
This whole file needs to be deleted. We don't run cloud-init on the PIT node, the daemons do not exist.

If the daemons are being installed as a result of these changes (e.g. csm-rpms:feature/livecd-gcp) then we need to cease doing that as well.

2022-01-26 01:04 UTC, rustydb commented on boxes/pit-common/files/resources/common/cloud/templates/cloud-init-network.tmpl
> +## template:jinja
Delete all cloud-init template files from pit-common.

2022-02-02 21:03 UTC, thiagonache reviewed
These are my findings.

2022-02-02 21:03 UTC, thiagonache commented on boxes/pit-common/root/etc/fstab
> +LABEL=PITDATA     /var/www/ephemeral           ext4   noauto,noatime              0  2
In the final image there's no entry for the root partition `/`

2022-02-02 21:03 UTC, thiagonache commented on boxes/pit-common/root/etc/sysconfig/network/ifcfg-bond0
> +NAME='Internal Interface'
this file should exist only in metal since GCP does not support real bond.

2022-02-02 21:03 UTC, thiagonache commented on boxes/pit-common/root/etc/sysconfig/network/ifcfg-lan0
> +NAME='External Site-Link'
this file should exist only on metal.

2022-02-02 21:03 UTC, thiagonache commented on boxes/pit-common/root/etc/sysconfig/network/ifroute-lan0
> +# Fill this in with your external route.
this file should only exist in metal

2022-02-09 21:03 UTC, heemstra approved these changes

2022-02-09 21:05 UTC, heemstra commented
/fast-forward

2022-02-09 21:05 UTC, merged