CASMINST-3853 - Move kernel install and lock to common layer
Cray-HPE/node-image-build pull request #171
Opened 2022-01-27 19:52 UTC by manderson-hpe

#### Summary and Scope
This change moves the kernel installation and locking to the common layer. 

This change enables kernel changes without rebuilding the base SLES layer, and further decouples the layer builds from the base installation. The change also removes duplicate kernel locking code, and a rogue installation and check of `jq`. `jq` has been moved to the base installation layer as it is required across the installation process for the rpm tools.

2022-01-27 19:57 UTC, rustydb requested changes

2022-01-27 19:57 UTC, rustydb commented on boxes/sles15-base/http/autoinst.template.xml
> +      <package>jq</package>
Alphabetize

2022-01-27 21:04 UTC, manderson-hpe commented on boxes/sles15-base/http/autoinst.template.xml
> +      <package>jq</package>
I apologize for this oversight.

2022-01-28 15:21 UTC, heemstra commented on boxes/sles15-base/variables.pkr.hcl
> -  default = "5.3.18-59.34.1"
Where/how is this getting set now?

2022-01-31 18:47 UTC, rustydb commented on boxes/sles15-base/variables.pkr.hcl
> -  default = "5.3.18-59.34.1"
I (maybe) assumed this was a default for local builds to work, but I'm now more curious too. I suppose CSM-rpms would override this when it does `zypper install` before it locks the kernel?

2022-02-01 15:13 UTC, heemstra commented on boxes/sles15-base/variables.pkr.hcl
> -  default = "5.3.18-59.34.1"
Looks like this is removing the duplicate code from sles15-base.  The same thing still exists in common.

2022-02-02 16:11 UTC, closed without merging