MTL-1660 Add Ansible Virtualenv for CSM
Cray-HPE/node-image-build pull request #224
Opened 2022-04-05 20:02 UTC by rustydb

#### Summary and Scope

- Fixes MTL-1660
- Relates to MTL-1513

##### Issue Type

- RFE Pull Request

This moves some of the Ansible init out of storage-ceph and into NCN common.
There is desire to have Ansible everywhere.

#### Prerequisites

- [ ] I have included documentation in my PR (or it is not required)
- [ ] I tested this on metal (e.g. an internal system, with hardware) (x) (if yes, please include results or a description of the test)
- [ ] I tested this on vshasta (if yes, please include results or a description of the test)
 
#### Idempotency
 

 
#### Risks and Mitigations

2022-04-05 20:05 UTC, heemstra commented on boxes/ncn-common/provisioners/common/ansible.sh
> +ANSIBLE_VERSION=2.11.10
`ANSIBLE_VERSION=${ANSIBLE_VERSION:-2.11.10}` ?

2022-04-05 20:07 UTC, heemstra approved these changes

2022-04-06 13:22 UTC, manderson-hpe requested changes

2022-04-06 13:22 UTC, manderson-hpe commented on boxes/ncn-common/provisioners/common/ansible.sh
> +mkdir -pv /etc/ansible
would something like `/opt/ansible` or `/opt/csm-ansible` be a place for this? Or `/usr/local`?

2022-04-06 16:29 UTC, rustydb commented on boxes/ncn-common/provisioners/common/ansible.sh
> +pip3 install boto3
@heemstra mentioned to me we probably need boto3. I also added netaddr since it commonly is needed for Ansible net modules.

2022-04-06 16:29 UTC, rustydb commented on boxes/ncn-common/provisioners/common/ansible.sh
> +pip3 install boto3
We should be able to add modules we need on-the-fly during install after activating the venv, but we could add more here if we'd like.

2022-04-06 16:30 UTC, rustydb commented on boxes/ncn-common/provisioners/common/ansible.sh
> +mkdir -pv /etc/ansible
I think so, I just chose `/etc/` since the other ones are here. I don't think `/etc/` is linux friendly. @heemstra any thoughts? `/opt/csm/anisible` or `/opt/ansible/csm`? or those places without "csm" in the name?

2022-04-07 18:15 UTC, manderson-hpe commented on boxes/ncn-common/provisioners/common/ansible.sh
> +mkdir -pv /etc/ansible
I would go with `/opt/csm/ansible` in this scenario. We can always change it.

2022-04-13 18:35 UTC, rustydb commented on boxes/ncn-common/provisioners/common/ansible.sh
> +mkdir -pv /etc/ansible
I'll leave it in `/etc/`

2022-04-13 18:36 UTC, rustydb commented
I rebased this on #229 , if this finishes it can merge after #229 or if #229 has a fluke failure _this_ can merge ahead of it.

2022-04-13 18:59 UTC, heemstra commented on boxes/ncn-common/provisioners/common/ansible.sh
> +mkdir -pv /etc/ansible
Didn't see this until now, sorry.  `/etc/ansible` is kinda the default/standard for ansible, but if there's a compelling reason to put it elsewhere, we can consider it.   Having it in a different 'root' from the others might annoy customers too?

2022-04-13 20:05 UTC, manderson-hpe commented on boxes/ncn-common/provisioners/common/ansible.sh
> +mkdir -pv /etc/ansible
`/etc/ansible` is the default for configuration that ansible uses if none is specified, more specifically the inventory. We're creating virtual environments that can be used for packages that run on the system. These should have a location outside of /etc. I think something like `/opt/csm` with the `ansible` venv installed in there makes more sense in this scenario. I'm not sure if it's moot but I don't want us putting things into /etc/ansible that might cause issues with ansible defaults in the future.

2022-04-13 20:12 UTC, heemstra commented on boxes/ncn-common/provisioners/common/ansible.sh
> +mkdir -pv /etc/ansible
I'm fine with that approach... if we also move the other virtualenvs that are already in /etc/ansible

2022-04-13 22:58 UTC, rustydb commented on boxes/ncn-common/provisioners/common/ansible.sh
> +mkdir -pv /etc/ansible
Fwiw I was going to go with `/opt` before making this PR, but I didn't want to move the existing envs in `/etc`.

Sine `/etc` is a convention already and since we merged the 1.2 counterpart for MTL-1660 I think we should leave it.

2022-04-14 00:50 UTC, heemstra approved these changes

2022-04-14 15:26 UTC, rustydb commented
/fast-forward

2022-04-14 15:27 UTC, merged