MTL-1668: Make base image an optional step in the build process
Cray-HPE/node-image-build pull request #232
Opened 2022-04-14 15:21 UTC by manderson-hpe

#### Summary and Scope

- Fixes [MTL-1668](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1668)
- Requires [MTL-1667](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1667)

##### Issue Type
- RFE Pull Request

This makes the NCN base image layer an option part of the build. 

#### Prerequisites

- [ ] I have included documentation in my PR (or it is not required)
- [ ] I tested this on metal (e.g. an internal system, with hardware) (x) (if yes, please include results or a description of the test)
- [ ] I tested this on vshasta (if yes, please include results or a description of the test)

2022-04-14 16:45 UTC, rustydb requested changes
Looks good, but I did have a concern about the `stableVersion` variable. That should default to the latest `[RELEASE]`.

2022-04-14 16:45 UTC, rustydb commented on Jenkinsfile.github
> +def stableVersion = "bb1b19a-1649947252636"
This looks like it's hardcoded the pipeline to a specific image, is this intentional for merge? Looks like it might be from testing the feature branch.

2022-04-14 16:45 UTC, rustydb commented on boxes/sles15-base/http/autoinst.template.xml
>        <package>sudo</package>
I thought we didn't need sudo anymore.

Also can we get rid of tar?

2022-04-14 16:45 UTC, rustydb commented on boxes/sles15-base/http/autoinst.template.xml
> +      <package>jq</package>
nit: add an XML comment saying why we need `jq` in the base image.

2022-04-14 17:47 UTC, manderson-hpe commented on Jenkinsfile.github
> +def stableVersion = "bb1b19a-1649947252636"
> Looks good, but I did have a concern about the `stableVersion` variable. That should default to the latest `[RELEASE]`.

The [RELEASE] doesn't work (for me?) and doesn't translate to GCP. My intention here, and I'm open to alternatives, was that we specify the specific version of the base image build that we want, and we will only really need to change it when we make a new base image and release it, such as SP2->SP3->SP4. A better variable name might be `stableBaseVersion`. As far as the value it would most likely be 0.3.1 going forward.

2022-04-14 17:47 UTC, manderson-hpe commented on boxes/sles15-base/http/autoinst.template.xml
>        <package>sudo</package>
I will give this a go, again. One of these three packages installs python. So a step downstream breaks because Python isn't installed yet. I will try to get these removed as part of this.

2022-04-18 19:41 UTC, rustydb commented on Jenkinsfile.github
> +def stableVersion = "bb1b19a-1649947252636"
We really need this automated. This works for me, it's for the artifactory API. For GCP it should be replaced on-the-fly, this was (is?) already handled.. is that broken now?

2022-04-24 02:00 UTC, rustydb commented
I plan on merging this tonight, so I rebased it for you.

2022-04-25 17:48 UTC, heemstra requested changes

2022-04-25 17:48 UTC, heemstra commented on boxes/ncn-common/files/scripts/common/create-kis-artifacts.sh
> +  cp /mnt/squashfs/boot/vmlinuz-${kernel_version} /squashfs/vmlinuz.kernel
I think this breaks ncn-image-modification.sh.  I need to verify...

2022-04-25 17:51 UTC, heemstra commented on boxes/ncn-common/files/scripts/common/create-kis-artifacts.sh
> +  cp /mnt/squashfs/boot/vmlinuz-${kernel_version} /squashfs/vmlinuz.kernel
I was wrong.  It would have broken the original version of that script, but the initrd/kernel handling was removed.  Resolving convo.

2022-04-25 17:51 UTC, heemstra approved these changes

2022-04-25 18:13 UTC, rustydb approved these changes

2022-04-25 21:47 UTC, rustydb commented
/fast-forward

2022-04-25 21:47 UTC, merged