CASMTRIAGE-3193 fix kdump not working
Cray-HPE/node-image-build pull request #235
Opened 2022-04-18 18:28 UTC by jacobsalmela

Signed-off-by: Jacob Salmela <jacob.salmela@hpe.com>

#### Summary and Scope

- Fixes CASMTRIAGE-3193
- Requires #
- Relates to #

##### Issue Type

- Bugfix Pull Request

In 1.0.x, there is a `ROOTIMG` entry in the node image's `/etc/fstab`.  This LABEL/mount isn't actually used anywhere except for when the image is built (https://stash.us.cray.com/projects/CASM-ARCHIVE/repos/node-image-sles15-base-archive/browse/http/autoinst.template.xml#126-135) as part of autoyast so it is a bit of a misnomer.

```
ncn-m001:~ # blkid -l -t "LABEL=ROOTIMG" -o device
ncn-m001:~ #
```

When the kdump initrd is generated, the kdump dracut module checks the running system for mount points and tries to convert them to kdump mount points.  Namely, it tries it's best to find `/` and create an entry for it in the kdump initrd at `/kdump/mnt0`.  In 1.0.x, the kdump dracut module has a non-fatal error, which ironically allowed the the script to continue to run.  

```
++ blkid -l -t LABEL=ROOTIMG -o device
+ _dev=
+ kdump_add_host_dev ''
+ local _dev=
+ [[  LABEL=ROOTRAID LABEL=SQFSRAID /kdump/mnt1/LiveOS/filesystem.squashfs #   == *\ \ * ]]
+ return
+ host_fs_types["$_dev"]=ext4
/usr/lib/dracut/modules.d/99kdump/module-setup.sh: line 83: host_fs_types["$_dev"]: bad array subscript
```

Since the `blkid` command does not return a device, the resulting fstab is empty.  In this case, this is what we want.  We explicitly define the kdump mount points when creating the kdump initrd because it needs to do some special things that the default kdump initrd does not work out of the box with: mount the SQFSRAID, mount the BOOTRAID, mount the r/o squash image from the SQFSRAID, and mount the overlay for writing.

In 1.2.x, this label was changed to SQFSRAID (https://github.com/Cray-HPE/node-image-build/blob/develop/boxes/sles15-base/http/autoinst.template.xml#L99-L101).  Since this label actually matches a RAID we setup, it returns a device:

```
ncn-m001:~ # blkid -l -t "LABEL=SQFSRAID" -o device
/dev/md125
```

the dracut kdump module then appends it to the kdump initrd's `fstab`.  In a simple situation where we just have a disk that matches that label, this would be expected and useful behavior.  However, since we have to create a custom initrd to handle the mounting of the overlay, this addition to our expliclty defined `fstab` now becomes a rogue entry.  

```
LABEL=SQFSRAID /kdump/mnt0 ext4 defaults 0 2 <------- this is the rogue entry
LABEL=ROOTRAID /kdump/mnt0/ xfs defaults 0 0
LABEL=SQFSRAID /kdump/mnt1/ xfs defaults 0 0
/kdump/mnt1/LiveOS/filesystem.squashfs /kdump/mnt2 squashfs ro,defaults 0 0
# overlay is mounted via mount_kdump_overlay.sh
```

When kdump loads up, it reads the `fstab` and tries to mount SQFSRAID at `/kdump/mnt0`.  This causes the error seen on the NCNs where it complains about a duplicate mount, which is true.  

```
[FAILED] Failed to mount /kdump/mnt0.
[DEPEND] Dependency failed for Local File Systems.
[ 2254.592928] systemd-fstab-generator[42629]: Failed to create unit file /run/systemd/generator/kdump-mnt0.mount, as it already exists. Duplicate entry in /etc/fstab?
[ 2258.896269] dracut-cmdline[42701]: mv: cannot stat '/etc/multipath.conf.kdump': No such file or directory
[FAILED] Failed to mount /kdump/mnt0.
[DEPEND] Dependency failed for Local File Systems.
[ 2261.998214] systemd-fstab-generator[42838]: Failed to create unit file /run/systemd/generator/kdump-mnt0.mount, as it already exists. Duplicate entry in /etc/fstab?
[FAILED] Failed to mount /k[ 2267.463597] systemd-fstab-generator[42873]: Failed to create unit file /run/systemd/generator/kdump-mnt0.mount, as it already exists. Duplicate entry in /etc/fstab?
```

Even if this wasn't the case, the mount would still fail since it is erronesouly defined as `ext4` instead of it's real file system type, `xfs`.  

Further enhancements and error handling are implemented in: MTL-1685 for csm 1.3

#### Prerequisites

- [x] I have included documentation in my PR (or it is not required)
- [x] I tested this on metal (e.g. an internal system, with hardware) (x) (if yes, please include results or a description of the test)
- [ ] I tested this on vshasta (if yes, please include results or a description of the test)
 
#### Idempotency
 
N/A
 
#### Risks and Mitigations
 
Low.

2022-04-18 21:01 UTC, rustydb submitted a review, later dismissed

2022-04-19 16:38 UTC, rustydb submitted a review, later dismissed

2022-04-19 18:09 UTC, heemstra requested changes

2022-04-19 18:09 UTC, heemstra commented on boxes/sles15-base/http/autoinst.template.xml
> +          <label>ROOTIMG</label>
This will reintroduce https://jira-pro.its.hpecorp.net:8443/browse/MTL-1616

2022-04-19 18:10 UTC, heemstra commented on boxes/sles15-base/http/autoinst.template.xml
> +          <label>ROOTIMG</label>
Specifically, it will break the systemd-remount-fs service.

2022-04-20 18:34 UTC, jacobsalmela commented on boxes/sles15-base/http/autoinst.template.xml
> +          <label>ROOTIMG</label>
Yes..this will need a bit more work.  For now, I'm removing the fstab entry in the kdump initrd.  And I'll address this in another PR.

2022-04-20 18:34 UTC, jacobsalmela commented on boxes/sles15-base/http/autoinst.template.xml
> +          <label>ROOTIMG</label>
Yes..this will need a bit more work.  For now, I'm removing the fstab entry in the kdump initrd.  And I'll address this in another PR.

2022-04-20 19:02 UTC, jacobsalmela commented
There is more investigation to do, so I'm adding in the known-workaround, which is an easy merge that gets us kdump back, and allows more time for developing a real solution

2022-04-20 20:08 UTC, rustydb approved these changes

2022-04-21 18:00 UTC, heemstra approved these changes

2022-04-21 19:27 UTC, heemstra commented
/fast-forward

2022-04-21 19:28 UTC, merged