MTL-1697 MTL-1698
Cray-HPE/node-image-build pull request #249
Opened 2022-04-25 10:26 UTC by jacobsalmela

#### Summary and Scope

- Fixes MTL-1968
- Fixes MTL-1697
- Relates to CASMINST-4413

##### Issue Type

- Bugfix Pull Request

Improves error handling of NTP script.  Specifically for situations when BSS is not installed/available.  Also adjusts the template path to the correct value.

Also adds two config options to enable remote chronyc commands.

#### Prerequisites

- [x] I have included documentation in my PR (or it is not required)
- [x] I tested this on metal (e.g. an internal system, with hardware) (x) (if yes, please include results or a description of the test)
- [ ] I tested this on vshasta (if yes, please include results or a description of the test)
 
#### Idempotency
 
Ran again and again and the config stayed the same
 
#### Risks and Mitigations
 
Low.

2022-04-25 13:53 UTC, rustydb commented on boxes/ncn-common/files/scripts/common/chrony/templates/cray.conf.j2
> +# listen for monitoring command packets (issued by chronyc)
nit: `# listen for monitoring command packets (issued by chronyc) on all interfaces`

2022-04-25 18:26 UTC, heemstra requested changes
Need to retarget for develop/csm-1.3

2022-04-26 12:01 UTC, jacobsalmela commented on boxes/ncn-common/files/scripts/common/chrony/templates/cray.conf.j2
> +# listen for monitoring command packets (issued by chronyc)
fixed in other PR

2022-04-26 12:01 UTC, jacobsalmela commented on boxes/ncn-common/files/scripts/common/chrony/csm_ntp.py
> +            pools = bss_data["ntp"]["pools"]
Fixed in other PR

2022-04-26 12:02 UTC, jacobsalmela commented
https://github.com/Cray-HPE/node-image-build/pull/250#issuecomment-1109708451

2022-05-02 18:11 UTC, heemstra submitted a review, later dismissed

2022-05-02 18:21 UTC, jacobsalmela commented on boxes/ncn-common/files/scripts/common/chrony/csm_ntp.py
> +            pools = bss_data["ntp"]["pools"]
Fixed here

2022-05-02 18:22 UTC, jacobsalmela commented on boxes/ncn-common/files/scripts/common/chrony/templates/cray.conf.j2
> +# listen for monitoring command packets (issued by chronyc)
Fixed here

2022-05-05 11:57 UTC, jacobsalmela commented
Closing again in favor of docs since this change is too much for 1.2

https://github.com/Cray-HPE/docs-csm/pull/1541

2022-05-05 11:57 UTC, closed without merging