MTL-1664, MTL-1697, MTL-1968 add ntp script to develop brach
Cray-HPE/node-image-build pull request #250
Opened 2022-04-25 10:37 UTC by jacobsalmela

#### Summary and Scope

- Relates to MTL-1664, MTL-1697, MTL-1968

##### Issue Type

- Bugfix Pull Request
- RFE Pull Request

Adds the NTP script to the develop branch

#### Prerequisites

- [x] I have included documentation in my PR (or it is not required)
- [x] I tested this on metal (e.g. an internal system, with hardware) (x) (if yes, please include results or a description of the test)
- [ ] I tested this on vshasta (if yes, please include results or a description of the test)
 
#### Idempotency
 
Deployed the template several times.
 
#### Risks and Mitigations
 
Low.

2022-04-25 13:55 UTC, rustydb requested changes

2022-04-25 13:55 UTC, rustydb commented on boxes/ncn-common/files/scripts/common/chrony/csm_ntp.py
> +        allow = bss_data["ntp"]["allow"]
Same as https://github.com/Cray-HPE/node-image-build/pull/249/files#r857640133

2022-04-25 17:53 UTC, manderson-hpe approved these changes
Approved with the changes that were already requested by @rustydb

2022-04-26 12:00 UTC, jacobsalmela commented on boxes/ncn-common/files/scripts/common/chrony/csm_ntp.py
> +        allow = bss_data["ntp"]["allow"]
Fixed

2022-04-26 12:01 UTC, jacobsalmela commented
Feedback implemented.  It was requested not to have this for 1.2, so only this PR will go.

2022-04-26 16:58 UTC, jacobsalmela commented
Rebasing onto Craig's branch in #231

2022-04-27 01:45 UTC, rustydb approved these changes

2022-04-27 01:46 UTC, merged