CASMNET-1549: Add sshd_config cloud-init step and template
Cray-HPE/node-image-build pull request #288
Opened 2022-05-18 19:02 UTC by manderson-hpe

#### Summary and Scope

- Fixes [CASMNET-1549](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1549)

##### Issue Type

- Bugfix Pull Request

Allows access to sshd on any network that is not CHN and CAN.

#### Prerequisites

- [ ] I have included documentation in my PR (or it is not required)
- [ ] I tested this on metal (e.g. an internal system, with hardware) (x) (if yes, please include results or a description of the test)
- [ ] I tested this on vshasta (if yes, please include results or a description of the test)
 
#### Idempotency
 

 
#### Risks and Mitigations

2022-05-18 20:14 UTC, rustydb requested changes

2022-05-18 20:14 UTC, rustydb commented on boxes/ncn-common/files/resources/common/cloud/templates/sshd_config.tmpl
> +# Your system has been configured with 'manage-sshd_config' set to true.
Where is this set? The function you added looks like it always runs.

2022-05-18 20:14 UTC, rustydb commented on boxes/ncn-common/files/scripts/metal/net-init.sh
> +function sshd_config() {
If you want this in net init, you should move this _after_ the IP test in the next block.

2022-05-18 20:14 UTC, rustydb commented on boxes/ncn-common/files/resources/common/cloud/templates/sshd_config.tmpl
> +PermitRootLogin 	yes
nit: all the things on the right side are wildy spaced different, can you align the values?

2022-05-18 20:33 UTC, manderson-hpe commented on boxes/ncn-common/files/resources/common/cloud/templates/sshd_config.tmpl
> +# Your system has been configured with 'manage-sshd_config' set to true.
It does always run. I'm either going to remove that or figure out where those vars are set and update it.

2022-05-18 20:35 UTC, manderson-hpe commented on boxes/ncn-common/files/resources/common/cloud/templates/sshd_config.tmpl
> +PermitRootLogin 	yes
This appears to be a github things. The editor it looks fine, but I think it is just the usage of tabs. 

<img width="381" alt="image" src="https://user-images.githubusercontent.com/84922849/169151156-d806b9cc-afde-47ef-9a57-46b8b02172c3.png">

2022-05-18 20:42 UTC, manderson-hpe commented on boxes/ncn-common/files/resources/common/cloud/templates/sshd_config.tmpl
> +PermitRootLogin 	yes
I removed the spacing and made it look like the default config file. Which is more consistent and easier to work with in code. It'll also be better this way for ansible management.

2022-05-18 20:43 UTC, manderson-hpe commented on boxes/ncn-common/files/scripts/metal/net-init.sh
> +function sshd_config() {
I have moved it to after the IP test but before the line that says it's all done.

2022-05-18 20:43 UTC, manderson-hpe commented on boxes/ncn-common/files/resources/common/cloud/templates/sshd_config.tmpl
> +# Your system has been configured with 'manage-sshd_config' set to true.
The only reference I could find for where I took this from is: https://github.com/Cray-HPE/metal-cloud-init/blob/41f93a6000406ca974a5b9f5dc5e29f97bb59edb/doc/examples/cloud-config-resolv-conf.txt so I have removed it.

2022-05-18 21:10 UTC, rustydb commented on boxes/ncn-common/files/resources/common/cloud/templates/sshd_config.tmpl
> +# Your system has been configured with 'manage-sshd_config' set to true.
Cool. The resolv and hosts files are cloud init toggles, I hadnt heard of the sshd one so I asked.

2022-05-18 21:10 UTC, rustydb approved these changes

2022-05-19 11:40 UTC, jacobsalmela commented
Did you test a booted image?  I have noticed the variables in the templates sometimes differ slightly.

2022-05-19 13:19 UTC, manderson-hpe commented
> Did you test a booted image? I have noticed the variables in the templates sometimes differ slightly.

No, I haven't tested a booted image. That's my goal when we can get a build working. As you pointed out, I presume it will fail, but I guess I won't know until I run it on a real system to see what the value are.

2022-05-20 16:17 UTC, rustydb commented
/fast-forward

2022-05-20 16:18 UTC, merged