CASMNET-1549: Add iptables rules and service for ssh
Cray-HPE/node-image-build pull request #308
Opened 2022-05-24 14:18 UTC by manderson-hpe

#### Summary and Scope

- Fixes [CASMNET-1549](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1549)
- Fixes [CASMNET-1568](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1568)

When the NCN is built,  the service is placed on the machine and enabled. The NCN boots, cloud-init kicks off net-init and the iptables_config function puts the iptables file into place, based on the BSS metadata for the networks. This template blocks on CAN and CHN networks. After cloud-init is done, the system finishes booting and the service is executed, which loads the iptables rules that work and allow 22 traffic destined for k8s. 

##### Issue Type

- Bugfix Pull Request

#### Testing

This was tested on Redbull and Mug.

Mug: The rules were loaded on all worker nodes and access was verified for UAI. We confirmed that ssh to the interface's IP was not allowed, but ssh traffic over the interface with a destination of a services within k8s was allowed.
Redbull: The images were booted and it was verified that the config files were properly generated. The service was properly initiated. And the rules were properly applied based on the available networks. It was then further verified that one cannot ssh to an NCN over the blocked network, but ssh access over the other networks is fine.

#### Prerequisites

- [x] I have included documentation in my PR (or it is not required)
- [x] I tested this on metal (e.g. an internal system, with hardware) (x) (if yes, please include results or a description of the test)
- [ ] I tested this on vshasta (if yes, please include results or a description of the test)

2022-05-24 14:23 UTC, rustydb requested changes

2022-05-24 14:23 UTC, rustydb commented on boxes/ncn-common/provisioners/common/setup.sh
> +mkdir -pv /etc/iptables
This should move into metal/setup.sh since the rest of your code is in a metal provisioner.

2022-05-24 15:57 UTC, manderson-hpe commented on boxes/ncn-common/provisioners/common/setup.sh
> +mkdir -pv /etc/iptables
I followed the "design pattern" of existing code. Folders are created in here that are used in the other location.

2022-05-24 15:59 UTC, denniswalker commented
Just need to confirm this doesn't break UAIs or CFS.

2022-05-24 16:06 UTC, rustydb commented on boxes/ncn-common/provisioners/common/setup.sh
> +mkdir -pv /etc/iptables
The "design pattern" is based on context, iow folders are created in here if they're used on all mediums. It looks like your service and resource are only used on metal, so making this folder in (for example) Google, doesn't make sense.

In other words, for organizational sake this folder should just be created on metal, since we don't have any iptables.

2022-05-24 17:04 UTC, manderson-hpe commented on boxes/ncn-common/provisioners/common/setup.sh
> +mkdir -pv /etc/iptables
Hmm, this is a good point. Should this be on all mediums, including GCP? Or should it just be on metal?

2022-05-24 20:23 UTC, rustydb commented on boxes/ncn-common/provisioners/common/setup.sh
> +mkdir -pv /etc/iptables
It's probably better to have it everywhere unless there's an explicit reason to have it confined to one medium.

2022-05-26 14:13 UTC, jacobsalmela submitted a review, later dismissed

2022-05-26 14:30 UTC, heemstra commented
Since you need to rebase anyway, please fix the license-check.

2022-05-26 20:28 UTC, rustydb approved these changes

2022-05-27 04:16 UTC, rustydb commented
/fast-forward

2022-05-27 04:20 UTC, rustydb commented
/fast-forward

2022-05-27 14:34 UTC, heemstra requested changes
Blocking merge pending details on compatibility with CFS and UAIs.

2022-05-27 14:37 UTC, heemstra commented
/fast-forward

2022-05-27 14:44 UTC, merged